spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ebm?useSSL=false
    username: ebm
    password: welcome@1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: 'true'
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: 'true'
