spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  datasource:
    url: jdbc:mysql://localhost:3306/ebm?allowPublicKeyRetrieval=true&useSSL=false
    username: 'root'
    password: 'Kakad@123'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
        format_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: 'true'    
    